/* tslint:disable */
/* eslint-disable */
/**
 * Keeper API
 * Keeper Budgeting App API Contract
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Account {
    'workspaceId'?: string;
    'id'?: string;
    'parentId'?: string;
    'type'?: string;
    /**
     * @type {string}
     * @memberof Account
     */
    'currency'?: string;
    'normalSide'?: NormalSide;
    'accountRole'?: AccountRole;
    'path'?: string;
    'name'?: string;
    'isActive'?: boolean;
    'createdAt'?: string;
    'deletedAt'?: string;
}



export const AccountClass = {
    Asset: 'ASSET',
    Liability: 'LIABILITY',
    Equity: 'EQUITY',
    Income: 'INCOME',
    Expense: 'EXPENSE',
} as const;

export type AccountClass = typeof AccountClass[keyof typeof AccountClass];


export interface AccountDTO {
    'id': string;
    'name': string;
    'type': string;
}

export const AccountRole = {
    Bank: 'BANK',
    Card: 'CARD',
    Cash: 'CASH',
    Category: 'CATEGORY',
    FxClearing: 'FX_CLEARING',
    Rounding: 'ROUNDING',
} as const;

export type AccountRole = typeof AccountRole[keyof typeof AccountRole];


export interface BudgetControllerBudgetDTO {
    'id': string;
    'name': string;
    'amount': number;
    'spent': number;
    'period': string;
}
export interface CreateBudgetDTO {
    'name'?: string;
    'amount'?: number;
    'period'?: string;
    'categoryId'?: string;
}
export interface CreateGoalDTO {
    'name'?: string;
    'targetAmount'?: number;
    'deadline'?: string;
    'currentAmount'?: number;
}
export interface CreateSubscriptionDTO {
    'name'?: string;
    'amount'?: number;
    'billingCycle'?: string;
    'nextBillingDate'?: string;
}
export interface CreateTransactionDTO {
    'type'?: string;
    'fromAccountId'?: string;
    'toAccountId'?: string;
    'account'?: CreateTransactionDTOAccountRef;
    'category'?: CreateTransactionDTOAccountRef;
    'name'?: string;
    'amount'?: number;
    'currency'?: string;
    'date'?: string;
    'notes'?: string;
    'payee'?: CreateTransactionDTOPayeeRef;
    'payeeName'?: string;
    'status'?: string;
}
export interface CreateTransactionDTOAccountRef {
    'id'?: string;
}
export interface CreateTransactionDTOPayeeRef {
    'name'?: string;
    'type'?: string;
}
export interface GoalControllerGoalDTO {
    'id': string;
    'name': string;
    'targetAmount': number;
    'currentAmount': number;
    'deadline': string;
}
export interface LedgerEntryDTO {
    'id': string;
    'amount': number;
    'currency': string;
    'account': AccountDTO;
}

export const NormalSide = {
    Debit: 'DEBIT',
    Credit: 'CREDIT',
} as const;

export type NormalSide = typeof NormalSide[keyof typeof NormalSide];


export interface SubscriptionControllerSubscriptionDTO {
    'id': string;
    'name': string;
    'amount': number;
    'billingCycle': string;
    'nextBillingDate': string;
}
export interface TransactionDTO {
    'id': string;
    'date': string;
    'notes': string;
    'name': string;
    'payee': any;
    'status': string;
    'entries': Array<LedgerEntryDTO>;
    'comments': Array<object>;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} workspaceId 
         * @param {Account} account 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAccount: async (workspaceId: string, account: Account, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('createAccount', 'workspaceId', workspaceId)
            // verify required parameter 'account' is not null or undefined
            assertParamExists('createAccount', 'account', account)
            const localVarPath = `/api/v1/accounts/{workspaceId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(account, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateBudgetDTO} createBudgetDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBudget: async (workspaceId: string, createBudgetDTO: CreateBudgetDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('createBudget', 'workspaceId', workspaceId)
            // verify required parameter 'createBudgetDTO' is not null or undefined
            assertParamExists('createBudget', 'createBudgetDTO', createBudgetDTO)
            const localVarPath = `/api/v1/budgets/{workspaceId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createBudgetDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateGoalDTO} createGoalDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGoal: async (workspaceId: string, createGoalDTO: CreateGoalDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('createGoal', 'workspaceId', workspaceId)
            // verify required parameter 'createGoalDTO' is not null or undefined
            assertParamExists('createGoal', 'createGoalDTO', createGoalDTO)
            const localVarPath = `/api/v1/goals/{workspaceId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createGoalDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateSubscriptionDTO} createSubscriptionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubscription: async (workspaceId: string, createSubscriptionDTO: CreateSubscriptionDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('createSubscription', 'workspaceId', workspaceId)
            // verify required parameter 'createSubscriptionDTO' is not null or undefined
            assertParamExists('createSubscription', 'createSubscriptionDTO', createSubscriptionDTO)
            const localVarPath = `/api/v1/subscriptions/{workspaceId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSubscriptionDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateTransactionDTO} createTransactionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTransaction: async (workspaceId: string, createTransactionDTO: CreateTransactionDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('createTransaction', 'workspaceId', workspaceId)
            // verify required parameter 'createTransactionDTO' is not null or undefined
            assertParamExists('createTransaction', 'createTransactionDTO', createTransactionDTO)
            const localVarPath = `/api/v1/transactions/{workspaceId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTransactionDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAccount: async (workspaceId: string, accountId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('deleteAccount', 'workspaceId', workspaceId)
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('deleteAccount', 'accountId', accountId)
            const localVarPath = `/api/v1/accounts/{workspaceId}/{accountId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)))
                .replace('{accountId}', encodeURIComponent(String(accountId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} budgetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBudget: async (workspaceId: string, budgetId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('deleteBudget', 'workspaceId', workspaceId)
            // verify required parameter 'budgetId' is not null or undefined
            assertParamExists('deleteBudget', 'budgetId', budgetId)
            const localVarPath = `/api/v1/budgets/{workspaceId}/{budgetId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)))
                .replace('{budgetId}', encodeURIComponent(String(budgetId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteGoal: async (workspaceId: string, goalId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('deleteGoal', 'workspaceId', workspaceId)
            // verify required parameter 'goalId' is not null or undefined
            assertParamExists('deleteGoal', 'goalId', goalId)
            const localVarPath = `/api/v1/goals/{workspaceId}/{goalId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)))
                .replace('{goalId}', encodeURIComponent(String(goalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubscription: async (workspaceId: string, subscriptionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('deleteSubscription', 'workspaceId', workspaceId)
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('deleteSubscription', 'subscriptionId', subscriptionId)
            const localVarPath = `/api/v1/subscriptions/{workspaceId}/{subscriptionId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)))
                .replace('{subscriptionId}', encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} transactionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTransaction: async (workspaceId: string, transactionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('deleteTransaction', 'workspaceId', workspaceId)
            // verify required parameter 'transactionId' is not null or undefined
            assertParamExists('deleteTransaction', 'transactionId', transactionId)
            const localVarPath = `/api/v1/transactions/{workspaceId}/{transactionId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)))
                .replace('{transactionId}', encodeURIComponent(String(transactionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} goalId 
         * @param {{ [key: string]: number; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fundGoal: async (workspaceId: string, goalId: string, requestBody: { [key: string]: number; }, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('fundGoal', 'workspaceId', workspaceId)
            // verify required parameter 'goalId' is not null or undefined
            assertParamExists('fundGoal', 'goalId', goalId)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('fundGoal', 'requestBody', requestBody)
            const localVarPath = `/api/v1/goals/{workspaceId}/{goalId}/fund`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)))
                .replace('{goalId}', encodeURIComponent(String(goalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAccounts: async (workspaceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('getAllAccounts', 'workspaceId', workspaceId)
            const localVarPath = `/api/v1/accounts/{workspaceId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTransactions: async (workspaceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('getAllTransactions', 'workspaceId', workspaceId)
            const localVarPath = `/api/v1/transactions/{workspaceId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBudgets: async (workspaceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('getBudgets', 'workspaceId', workspaceId)
            const localVarPath = `/api/v1/budgets/{workspaceId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} months 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboard: async (months: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'months' is not null or undefined
            assertParamExists('getDashboard', 'months', months)
            const localVarPath = `/api/analytics/dashboard`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (months !== undefined) {
                localVarQueryParameter['months'] = months;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGoals: async (workspaceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('getGoals', 'workspaceId', workspaceId)
            const localVarPath = `/api/v1/goals/{workspaceId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriptions: async (workspaceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('getSubscriptions', 'workspaceId', workspaceId)
            const localVarPath = `/api/v1/subscriptions/{workspaceId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} accountId 
         * @param {Account} account 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAccount: async (workspaceId: string, accountId: string, account: Account, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('updateAccount', 'workspaceId', workspaceId)
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('updateAccount', 'accountId', accountId)
            // verify required parameter 'account' is not null or undefined
            assertParamExists('updateAccount', 'account', account)
            const localVarPath = `/api/v1/accounts/{workspaceId}/{accountId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)))
                .replace('{accountId}', encodeURIComponent(String(accountId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(account, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} budgetId 
         * @param {CreateBudgetDTO} createBudgetDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBudget: async (workspaceId: string, budgetId: string, createBudgetDTO: CreateBudgetDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('updateBudget', 'workspaceId', workspaceId)
            // verify required parameter 'budgetId' is not null or undefined
            assertParamExists('updateBudget', 'budgetId', budgetId)
            // verify required parameter 'createBudgetDTO' is not null or undefined
            assertParamExists('updateBudget', 'createBudgetDTO', createBudgetDTO)
            const localVarPath = `/api/v1/budgets/{workspaceId}/{budgetId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)))
                .replace('{budgetId}', encodeURIComponent(String(budgetId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createBudgetDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} goalId 
         * @param {CreateGoalDTO} createGoalDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateGoal: async (workspaceId: string, goalId: string, createGoalDTO: CreateGoalDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('updateGoal', 'workspaceId', workspaceId)
            // verify required parameter 'goalId' is not null or undefined
            assertParamExists('updateGoal', 'goalId', goalId)
            // verify required parameter 'createGoalDTO' is not null or undefined
            assertParamExists('updateGoal', 'createGoalDTO', createGoalDTO)
            const localVarPath = `/api/v1/goals/{workspaceId}/{goalId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)))
                .replace('{goalId}', encodeURIComponent(String(goalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createGoalDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} subscriptionId 
         * @param {CreateSubscriptionDTO} createSubscriptionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSubscription: async (workspaceId: string, subscriptionId: string, createSubscriptionDTO: CreateSubscriptionDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('updateSubscription', 'workspaceId', workspaceId)
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('updateSubscription', 'subscriptionId', subscriptionId)
            // verify required parameter 'createSubscriptionDTO' is not null or undefined
            assertParamExists('updateSubscription', 'createSubscriptionDTO', createSubscriptionDTO)
            const localVarPath = `/api/v1/subscriptions/{workspaceId}/{subscriptionId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)))
                .replace('{subscriptionId}', encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSubscriptionDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} transactionId 
         * @param {CreateTransactionDTO} createTransactionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTransaction: async (workspaceId: string, transactionId: string, createTransactionDTO: CreateTransactionDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('updateTransaction', 'workspaceId', workspaceId)
            // verify required parameter 'transactionId' is not null or undefined
            assertParamExists('updateTransaction', 'transactionId', transactionId)
            // verify required parameter 'createTransactionDTO' is not null or undefined
            assertParamExists('updateTransaction', 'createTransactionDTO', createTransactionDTO)
            const localVarPath = `/api/v1/transactions/{workspaceId}/{transactionId}`
                .replace('{workspaceId}', encodeURIComponent(String(workspaceId)))
                .replace('{transactionId}', encodeURIComponent(String(transactionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTransactionDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} workspaceId 
         * @param {Account} account 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAccount(workspaceId: string, account: Account, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Account>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAccount(workspaceId, account, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateBudgetDTO} createBudgetDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBudget(workspaceId: string, createBudgetDTO: CreateBudgetDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BudgetControllerBudgetDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBudget(workspaceId, createBudgetDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createBudget']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateGoalDTO} createGoalDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createGoal(workspaceId: string, createGoalDTO: CreateGoalDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GoalControllerGoalDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createGoal(workspaceId, createGoalDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createGoal']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateSubscriptionDTO} createSubscriptionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSubscription(workspaceId: string, createSubscriptionDTO: CreateSubscriptionDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionControllerSubscriptionDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSubscription(workspaceId, createSubscriptionDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateTransactionDTO} createTransactionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTransaction(workspaceId: string, createTransactionDTO: CreateTransactionDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTransaction(workspaceId, createTransactionDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createTransaction']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAccount(workspaceId: string, accountId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAccount(workspaceId, accountId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} budgetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBudget(workspaceId: string, budgetId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteBudget(workspaceId, budgetId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteBudget']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteGoal(workspaceId: string, goalId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteGoal(workspaceId, goalId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteGoal']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSubscription(workspaceId: string, subscriptionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSubscription(workspaceId, subscriptionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} transactionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTransaction(workspaceId: string, transactionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTransaction(workspaceId, transactionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteTransaction']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} goalId 
         * @param {{ [key: string]: number; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fundGoal(workspaceId: string, goalId: string, requestBody: { [key: string]: number; }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GoalControllerGoalDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fundGoal(workspaceId, goalId, requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.fundGoal']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllAccounts(workspaceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Account>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllAccounts(workspaceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllAccounts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllTransactions(workspaceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TransactionDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllTransactions(workspaceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllTransactions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBudgets(workspaceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BudgetControllerBudgetDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBudgets(workspaceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getBudgets']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} months 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDashboard(months: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDashboard(months, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getDashboard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGoals(workspaceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GoalControllerGoalDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGoals(workspaceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getGoals']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubscriptions(workspaceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SubscriptionControllerSubscriptionDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubscriptions(workspaceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSubscriptions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} accountId 
         * @param {Account} account 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAccount(workspaceId: string, accountId: string, account: Account, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Account>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAccount(workspaceId, accountId, account, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} budgetId 
         * @param {CreateBudgetDTO} createBudgetDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateBudget(workspaceId: string, budgetId: string, createBudgetDTO: CreateBudgetDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BudgetControllerBudgetDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateBudget(workspaceId, budgetId, createBudgetDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateBudget']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} goalId 
         * @param {CreateGoalDTO} createGoalDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateGoal(workspaceId: string, goalId: string, createGoalDTO: CreateGoalDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GoalControllerGoalDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateGoal(workspaceId, goalId, createGoalDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateGoal']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} subscriptionId 
         * @param {CreateSubscriptionDTO} createSubscriptionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSubscription(workspaceId: string, subscriptionId: string, createSubscriptionDTO: CreateSubscriptionDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionControllerSubscriptionDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSubscription(workspaceId, subscriptionId, createSubscriptionDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} transactionId 
         * @param {CreateTransactionDTO} createTransactionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTransaction(workspaceId: string, transactionId: string, createTransactionDTO: CreateTransactionDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTransaction(workspaceId, transactionId, createTransactionDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateTransaction']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {string} workspaceId 
         * @param {Account} account 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAccount(workspaceId: string, account: Account, options?: RawAxiosRequestConfig): AxiosPromise<Account> {
            return localVarFp.createAccount(workspaceId, account, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateBudgetDTO} createBudgetDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBudget(workspaceId: string, createBudgetDTO: CreateBudgetDTO, options?: RawAxiosRequestConfig): AxiosPromise<BudgetControllerBudgetDTO> {
            return localVarFp.createBudget(workspaceId, createBudgetDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateGoalDTO} createGoalDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGoal(workspaceId: string, createGoalDTO: CreateGoalDTO, options?: RawAxiosRequestConfig): AxiosPromise<GoalControllerGoalDTO> {
            return localVarFp.createGoal(workspaceId, createGoalDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateSubscriptionDTO} createSubscriptionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubscription(workspaceId: string, createSubscriptionDTO: CreateSubscriptionDTO, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionControllerSubscriptionDTO> {
            return localVarFp.createSubscription(workspaceId, createSubscriptionDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {CreateTransactionDTO} createTransactionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTransaction(workspaceId: string, createTransactionDTO: CreateTransactionDTO, options?: RawAxiosRequestConfig): AxiosPromise<TransactionDTO> {
            return localVarFp.createTransaction(workspaceId, createTransactionDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAccount(workspaceId: string, accountId: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.deleteAccount(workspaceId, accountId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} budgetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBudget(workspaceId: string, budgetId: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.deleteBudget(workspaceId, budgetId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} goalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteGoal(workspaceId: string, goalId: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.deleteGoal(workspaceId, goalId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubscription(workspaceId: string, subscriptionId: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.deleteSubscription(workspaceId, subscriptionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} transactionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTransaction(workspaceId: string, transactionId: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.deleteTransaction(workspaceId, transactionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} goalId 
         * @param {{ [key: string]: number; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fundGoal(workspaceId: string, goalId: string, requestBody: { [key: string]: number; }, options?: RawAxiosRequestConfig): AxiosPromise<GoalControllerGoalDTO> {
            return localVarFp.fundGoal(workspaceId, goalId, requestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAccounts(workspaceId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<Account>> {
            return localVarFp.getAllAccounts(workspaceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTransactions(workspaceId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionDTO>> {
            return localVarFp.getAllTransactions(workspaceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBudgets(workspaceId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<BudgetControllerBudgetDTO>> {
            return localVarFp.getBudgets(workspaceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} months 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboard(months: number, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.getDashboard(months, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGoals(workspaceId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GoalControllerGoalDTO>> {
            return localVarFp.getGoals(workspaceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriptions(workspaceId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<SubscriptionControllerSubscriptionDTO>> {
            return localVarFp.getSubscriptions(workspaceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} accountId 
         * @param {Account} account 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAccount(workspaceId: string, accountId: string, account: Account, options?: RawAxiosRequestConfig): AxiosPromise<Account> {
            return localVarFp.updateAccount(workspaceId, accountId, account, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} budgetId 
         * @param {CreateBudgetDTO} createBudgetDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBudget(workspaceId: string, budgetId: string, createBudgetDTO: CreateBudgetDTO, options?: RawAxiosRequestConfig): AxiosPromise<BudgetControllerBudgetDTO> {
            return localVarFp.updateBudget(workspaceId, budgetId, createBudgetDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} goalId 
         * @param {CreateGoalDTO} createGoalDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateGoal(workspaceId: string, goalId: string, createGoalDTO: CreateGoalDTO, options?: RawAxiosRequestConfig): AxiosPromise<GoalControllerGoalDTO> {
            return localVarFp.updateGoal(workspaceId, goalId, createGoalDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} subscriptionId 
         * @param {CreateSubscriptionDTO} createSubscriptionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSubscription(workspaceId: string, subscriptionId: string, createSubscriptionDTO: CreateSubscriptionDTO, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionControllerSubscriptionDTO> {
            return localVarFp.updateSubscription(workspaceId, subscriptionId, createSubscriptionDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} transactionId 
         * @param {CreateTransactionDTO} createTransactionDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTransaction(workspaceId: string, transactionId: string, createTransactionDTO: CreateTransactionDTO, options?: RawAxiosRequestConfig): AxiosPromise<TransactionDTO> {
            return localVarFp.updateTransaction(workspaceId, transactionId, createTransactionDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {string} workspaceId 
     * @param {Account} account 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createAccount(workspaceId: string, account: Account, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createAccount(workspaceId, account, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {CreateBudgetDTO} createBudgetDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createBudget(workspaceId: string, createBudgetDTO: CreateBudgetDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createBudget(workspaceId, createBudgetDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {CreateGoalDTO} createGoalDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createGoal(workspaceId: string, createGoalDTO: CreateGoalDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createGoal(workspaceId, createGoalDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {CreateSubscriptionDTO} createSubscriptionDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSubscription(workspaceId: string, createSubscriptionDTO: CreateSubscriptionDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createSubscription(workspaceId, createSubscriptionDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {CreateTransactionDTO} createTransactionDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTransaction(workspaceId: string, createTransactionDTO: CreateTransactionDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createTransaction(workspaceId, createTransactionDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} accountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteAccount(workspaceId: string, accountId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteAccount(workspaceId, accountId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} budgetId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteBudget(workspaceId: string, budgetId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteBudget(workspaceId, budgetId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} goalId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteGoal(workspaceId: string, goalId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteGoal(workspaceId, goalId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} subscriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSubscription(workspaceId: string, subscriptionId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteSubscription(workspaceId, subscriptionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} transactionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTransaction(workspaceId: string, transactionId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteTransaction(workspaceId, transactionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} goalId 
     * @param {{ [key: string]: number; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fundGoal(workspaceId: string, goalId: string, requestBody: { [key: string]: number; }, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).fundGoal(workspaceId, goalId, requestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllAccounts(workspaceId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllAccounts(workspaceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllTransactions(workspaceId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllTransactions(workspaceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getBudgets(workspaceId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getBudgets(workspaceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} months 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDashboard(months: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getDashboard(months, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getGoals(workspaceId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getGoals(workspaceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSubscriptions(workspaceId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSubscriptions(workspaceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} accountId 
     * @param {Account} account 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateAccount(workspaceId: string, accountId: string, account: Account, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateAccount(workspaceId, accountId, account, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} budgetId 
     * @param {CreateBudgetDTO} createBudgetDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateBudget(workspaceId: string, budgetId: string, createBudgetDTO: CreateBudgetDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateBudget(workspaceId, budgetId, createBudgetDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} goalId 
     * @param {CreateGoalDTO} createGoalDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateGoal(workspaceId: string, goalId: string, createGoalDTO: CreateGoalDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateGoal(workspaceId, goalId, createGoalDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} subscriptionId 
     * @param {CreateSubscriptionDTO} createSubscriptionDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateSubscription(workspaceId: string, subscriptionId: string, createSubscriptionDTO: CreateSubscriptionDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateSubscription(workspaceId, subscriptionId, createSubscriptionDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} transactionId 
     * @param {CreateTransactionDTO} createTransactionDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateTransaction(workspaceId: string, transactionId: string, createTransactionDTO: CreateTransactionDTO, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateTransaction(workspaceId, transactionId, createTransactionDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



